language: swift

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - make setup-linux
    - os: osx
      osx_image: xcode7.3
      before_install:
        - make setup-osx

script:
  - swift build

notifications:
  email:
    on_success: never
    on_failure: change