language: swift

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

before_install:
  - make ci-setup

script:
  - swift build

notifications:
  email:
    on_success: never
    on_failure: change