os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - bash TestRedis/install_redis_local.sh
  - curl -sL https://gist.githubusercontent.com/czechboy0/6539d0586a2c080e403c/raw/fa5300ae2764f7c8b3c4d835f2d14d7cc3ab1ebf/swiftenv-install.sh | bash
script:
  - swift build
  - export PATH="$PWD/redis-stable/src/:$PATH"
  - make redis-start
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make xctest; fi
  - .build/debug/RedbirdExample
notifications:
  email:
    on_success: never
    on_failure: change



