os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - curl -sL https://gist.githubusercontent.com/czechboy0/77c97b4ced37b512d1a2/raw/43dc2c4fe4c2537f368c23f4a211c77cebabcda2/redis-local-install.sh | bash
  - curl -sL https://gist.githubusercontent.com/czechboy0/6539d0586a2c080e403c/raw/66eae4e588fd43f00d85ca768db46f7ceae89566/swiftenv-install.sh | bash
script:
  - swift build
  - export PATH="$PWD/redis-stable/src/:$PATH"
  - make redis-start
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make xctest; fi
  - .build/debug/RedbirdExample
notifications:
  email:
    on_success: never
    on_failure: change



